### ISSUE TITLE
make harmonized_table.db: no sars_cov_2_diag_pcr_ct_value_2 column

### ISSUE THREAD

**Issue by turbomam** [INCATools/biosample-analysis#58]
```bash
% time make target/harmonized_table.db
```

> % time make target/harmonized_table.db
python ./util/save-harmonized-table-to-sqlite.py target/harmonized-table.tsv target/harmonized_table.db
reading chunks
saving as sqlite3
Traceback (most recent call last):
  File "./util/save-harmonized-table-to-sqlite.py", line 24, in <module>
    chunk.to_sql(name='biosample', con=con, if_exists='append', index=False)
  File "/Users/MAM/Documents/gitrepos/biosample-analysis/venv/lib/python3.8/site-packages/pandas/core/generic.py", line 2602, in to_sql
    sql.to_sql(
  File "/Users/MAM/Documents/gitrepos/biosample-analysis/venv/lib/python3.8/site-packages/pandas/io/sql.py", line 589, in to_sql
    pandas_sql.to_sql(
  File "/Users/MAM/Documents/gitrepos/biosample-analysis/venv/lib/python3.8/site-packages/pandas/io/sql.py", line 1828, in to_sql
    table.insert(chunksize, method)
  File "/Users/MAM/Documents/gitrepos/biosample-analysis/venv/lib/python3.8/site-packages/pandas/io/sql.py", line 830, in insert
    exec_insert(conn, keys, chunk_iter)
  File "/Users/MAM/Documents/gitrepos/biosample-analysis/venv/lib/python3.8/site-packages/pandas/io/sql.py", line 1555, in _execute_insert
    conn.executemany(self.insert_statement(num_rows=1), data_list)
sqlite3.OperationalError: table biosample has no column named sars_cov_2_diag_pcr_ct_value_2
make: *** [target/harmonized_table.db] Error 1
make target/harmonized_table.db  694.43s user 153.44s system 95% cpu 14:43.92 total

**Comment by turbomam** [comment]
Was there a`sars_cov_2_diag_pcr_ct_value_2` column in an older biosample sqlite database?

_You could could probably do the following with a single AWK command!_

```bash
sqlite3 harmonized_table.db '.schema biosample' '.exit' | \
    grep 'TEXT' | sed 's/  "//' | sed 's/" TEXT,//' | grep '^s' | sort
```

**No, that column wasn't in there before**

> salinity
salinity_meth
salt_regm
same_as
samp_collect_device
samp_mat_process
samp_salinity
samp_size
samp_sort_meth
samp_store_dur
samp_store_loc
samp_store_temp
samp_vol_we_dna_ext
sample_name
sample_type
season_environment
secondary_treatment
sediment_type
serogroup
serotype
serovar
sewage_type
sex
sexual_act
sieving
silicate
size_frac
slope_aspect
slope_gradient
sludge_retent_time
smoker
sodium
soil_type
soil_type_meth
soluble_inorg_mat
soluble_org_mat
soluble_react_phosp
source_material_id
source_name
source_uvig
space_typ_state
special_diet
specimen_voucher
standing_water_regm
status
status_date
store_cond
strain
stud_book_number
study_complt_stat
study_design
study_disease
study_name
sub_species
subclone
subgroup
subject_is_affected
submitted_sample_id
submitted_subject_id
submitter_handle
subspecf_gen_lin
subsrc_note
substrain
substrate
substructure_type
subtype
sulfate
sulfide
super_population_code
super_population_description
surf_air_cont
surf_humidity
surf_material
surf_moisture
surf_moisture_ph
surf_temp
suspend_part_matter
suspend_solids

**Comment by turbomam** [comment]
PS running this for the first time in PyCharm requested to install `importlib-metadata==1.7.0`

**Comment by turbomam** [comment]
That `sars_cov_2_diag_pcr_ct_value_2` column must be new since the older pull of `biosample_set.xml.gz`

```bash
head -n 1 target/harmonized-table.tsv | tr '\t' '\n' | sort | grep '^s'
```

> salinity
salinity_meth
salt_regm
same_as
samp_collect_device
samp_mat_process
samp_salinity
samp_size
samp_sort_meth
samp_store_dur
samp_store_loc
samp_store_temp
samp_vol_we_dna_ext
sample_name
sample_type
sars_cov_2_diag_gene_name_1
sars_cov_2_diag_gene_name_2
sars_cov_2_diag_pcr_ct_value_1
sars_cov_2_diag_pcr_ct_value_2
season_environment
secondary_treatment
sediment_type
sequenced_by
serogroup
serotype
serovar
sewage_type
sex
sexual_act
sieving
silicate
size_frac
slope_aspect
slope_gradient
sludge_retent_time
smoker
sodium
soil_type
soil_type_meth
solar_irradiance
soluble_inorg_mat
soluble_org_mat
soluble_react_phosp
source_material_id
source_name
source_uvig
space_typ_state
special_diet
specimen_voucher
standing_water_regm
status
status_date
store_cond
strain
stud_book_number
study_complt_stat
study_design
study_disease
study_name
sub_species
subclone
subgroup
subject_is_affected
submitted_sample_id
submitted_subject_id
submitter_handle
subspecf_gen_lin
subsrc_note
substrain
substrate
substructure_type
subtype
sulfate
sulfide
super_population_code
super_population_description
surf_air_cont
surf_humidity
surf_material
surf_moisture
surf_moisture_ph
surf_temp
suspend_part_matter
suspend_solids

**Comment by turbomam** [comment]
Yeah, that really is a column in this more recent biosample file.

After stepping through `util/save-harmonized-table-to-sqlite.py` far enought to read all of `target/harmonized-table.tsv` into `chunks[]`:

```python
print(chunks[0]['sars_cov_2_diag_gene_name_1'])
```

> 0         NaN
1         NaN
2         NaN
3         NaN
4         NaN
         ... 
999995    NaN
999996    NaN
999997    NaN
999998    NaN
999999    NaN
Name: sars_cov_2_diag_gene_name_1, Length: 1000000, dtype: object

**Comment by turbomam** [comment]
[Some discussion about legal sqlite column names](https://stackoverflow.com/questions/3373234/what-sqlite-column-name-can-be-cannot-be/45775719) 

Is there a column name max length? Probably not. https://www.sqlite.org/limits.html
